### ISSUE TITLE
wwidd is not opening in ubuntu 12.04

### ISSUE THREAD

**Issue by ghost** [wwidd/wwidd#10]
No error but wwidd is not opening in ubuntu 12.04 just a flash of terminal n nothing :(

**Comment by danstocker** [comment]
Have you tried this? https://github.com/wwidd/wwidd/wiki/Installing-on-Ubuntu-12.04-from-scratch
If this does not work try opening a terminal and run `start.sh` from there. See if you can catch an error message that way.

**Comment by danstocker** [comment]
By the way Wwidd is being completely rewritten for [node-webkit](https://github.com/rogerwang/node-webkit) which should make distribution and platform independence a lot easier. I can't put a date on the release though.
