### ISSUE TITLE
Sort videos by rating

### ISSUE THREAD

**Issue by london111** [wwidd/wwidd#2]
Is it possible to sort the videos by rating?

**Comment by danstocker** [comment]
Not yet. There's a discovery feature planned for version 0.5 which will address this issue.

**Comment by wesly-zz** [comment]
I second this feature. I'd like to filter/search on ratings (e.g. display all 5 star videos).

**Comment by danstocker** [comment]
Check out this early screenshot from the next release (0.5) http://fb.me/1bKLfVLWA

**Comment by wesly-zz** [comment]
Awesome Dan! The screenshot looks really nice! Can't wait till the next release :)
